# Generated by Django 4.1.12 on 2023-10-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('kids', models.ManyToManyField(related_name='kids', to='accounts.user')),
                ('parents', models.ManyToManyField(related_name='parents', to='accounts.user')),
            ],
        ),
    ]
