# Generated by Django 4.1.12 on 2023-10-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expenses',
        ),
    ]
