# Generated by Django 4.1.12 on 2023-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Gilad', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
