# Generated by Django 4.1.12 on 2023-10-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_receiptproduct_shop'),
        ('accounts', '0005_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(related_name='favorite_products', to='shops.product'),
        ),
    ]
