# Generated by Django 4.1.12 on 2023-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_favorite_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_id',
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
