# Generated by Django 4.1.12 on 2023-10-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_of_measurement',
            name='count',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
