# Generated by Django 4.1.12 on 2023-10-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_unit_of_measurement_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipet_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.product')),
                ('recipet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.recipet')),
            ],
        ),
    ]
