# Generated by Django 4.1.12 on 2023-10-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_recipet_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipet_Product',
            new_name='RecipetProduct',
        ),
    ]
