# Generated by Django 4.1.12 on 2023-10-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_rename_recipet_product_recipetproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipetProduct',
            new_name='Recipet_Product',
        ),
    ]
