# Generated by Django 4.1.12 on 2023-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_receiptproduct_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=300)),
            ],
        ),
    ]
