# Generated by Django 4.1.12 on 2023-10-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_payment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_type',
            old_name='icon',
            new_name='icon_class',
        ),
    ]
