# Generated by Django 4.1.12 on 2023-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_rename_recipet_product_recipetproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops_net',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
