# Generated by Django 4.1.12 on 2023-10-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_rename_icon_payment_type_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shops.payment_type'),
        ),
    ]
