# Generated by Django 4.1.12 on 2023-10-31 14:29

from django.db import migrations, models
import django.utils.timezone
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_receipt_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to=shops.models.receipt_pdf_upload_path),
            preserve_default=False,
        ),
    ]
