# Generated by Django 4.1.12 on 2023-10-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense_types',
            new_name='Expense_type',
        ),
    ]
