# Generated by Django 4.1.12 on 2023-10-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_expense_types_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recipt',
            field=models.BooleanField(default=True),
        ),
    ]
