# Generated by Django 4.1.12 on 2023-10-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_expense_description_alter_expense_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='is_recipt',
            new_name='is_receipt',
        ),
    ]
